version: "3.7"

volumes:
  postgres-kapibara:
  pgadmin-kapibara:

networks:
  kapibara-net:

services:
  database:
    container_name: kapibara-postgres
    image: postgres
    restart: unless-stopped
    networks:
      - kapibara-net
    ports:
      - ":5432"
    environment:
      - POSTGRES_DB=kapibara
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-kapibara:/var/lib/postgresql/data

  backend:
    container_name: kapibara-backend
    build: ./backend/
    restart: unless-stopped
    networks:
      - kapibara-net
    depends_on:
      - database
    ports:
      - "127.0.0.1:8004:8080"

  frontend:
    container_name: kapibara-frontend
    build: ./frontend/
    restart: unless-stopped
    networks:
      - kapibara-net
    depends_on:
      - database
    ports:
      - "127.0.0.1:8003:80"
