version: "3.7"

services:
  postgres:
    container_name: kapibara-postgres
    image: postgres
    restart: unless-stopped
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=kapibara
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - kapibara-postgres-data:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: kapibara-pgadmin
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "127.0.0.1:5500:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@fastapi.com
  #     PGADMIN_DEFAULT_PASSWORD: fastapi
  #   volumes:
  #     - kapibara-pgadmin-data:/var/lib/pgadmin

  # parser:
  #   build: ./services/parser/
  #   container_name: parser
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres

  # backend:
  #   build: ./backend/
  #   container_name: backend
  #   restart: unless-stopped
  #   volumes:
  #     - ./services/backend/src:/code/
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8080:80"

  # frontend:
  #   build: ./frontend/
  #   container_name: frontend
  #   volumes:
  #     - './services/frontend:/code/'
  #     - '/code/node_modules'
  #   depends_on:
  #     - backend
  #   ports:
  #     - "8081:5173"
  # dbeaver:
  #   image: dbeaver/cloudbeaver:latest
  #   container_name: dbeaver
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "5600:8978"

volumes:
  kapibara-postgres-data:
  kapibara-pgadmin-data:
