services:
  database:
    container_name: kapibara-postgres
    image: postgres
    restart: unless-stopped
    ports:
      - "127.0.0.1:54321:5432"
    environment:
      - POSTGRES_DB=kapibara-postgres
      - POSTGRES_USER=kapibara-postgres
      - POSTGRES_PASSWORD=kapibara-postgres
    volumes:
      - kapibara-postgres-data:/var/lib/postgresql/data

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: kapibara-pgadmin
  #   restart: unless-stopped
  #   depends_on:
  #     - database
  #   ports:
  #     - "127.0.0.1:808:80"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@fastapi.com
  #     PGADMIN_DEFAULT_PASSWORD: fastapi
  #   volumes:
  #     - kapibara-pgadmin-data:/var/lib/pgadmin

  parser:
    build: ./parser/
    container_name: kapibara-parser
    restart: unless-stopped
    depends_on:
      - database

  backend:
    build: ./backend/
    container_name: kapibara-backend
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "127.0.0.1:8080:80"

  frontend:
    build: ./frontend/
    container_name: kapibara-frontend
    depends_on:
      - backend
    ports:
      - "127.0.0.1:8081:5173"

volumes:
  kapibara-postgres-data:
  kapibara-pgadmin-data:
