"""add: In document index eo_number

Revision ID: 5d6a9c7cc08f
Revises: 0220392adb46
Create Date: 2024-09-18 16:47:06.547086

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d6a9c7cc08f"
down_revision: Union[str, None] = "0220392adb46"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("documents_id_name_eo_number_key", "documents", type_="unique")
    op.create_index("idx_documents_eo_number", "documents", ["eo_number"], unique=True)
    op.create_unique_constraint(None, "documents", ["id", "eo_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "documents", type_="unique")
    op.drop_index("idx_documents_eo_number", table_name="documents")
    op.create_unique_constraint(
        "documents_id_name_eo_number_key", "documents", ["id", "name", "eo_number"]
    )
    # ### end Alembic commands ###
