"""add: document_types.external_id index

Revision ID: 8b5d02cf7c09
Revises: 4f85a1c82127
Create Date: 2024-05-02 16:11:14.375191

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8b5d02cf7c09"
down_revision: Union[str, None] = "4f85a1c82127"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_document_types_external_id", "document_types", ["external_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_document_types_external_id", table_name="document_types")
    # ### end Alembic commands ###
