"""upgrade

Revision ID: c949ac84db6f
Revises: 7ec6bdb5288d
Create Date: 2024-09-17 18:35:19.319162

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c949ac84db6f"
down_revision: Union[str, None] = "7ec6bdb5288d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "documents", "eo_number", existing_type=sa.VARCHAR(length=16), nullable=True
    )
    op.alter_column("documents", "complex_name", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "documents", "pages_count", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "documents", "pdf_file_length", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("documents", "name", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("documents", "document_date", existing_type=sa.DATE(), nullable=True)
    op.alter_column(
        "documents",
        "signatory_authority_id",
        existing_type=sa.VARCHAR(length=256),
        nullable=True,
    )
    op.alter_column(
        "documents",
        "document_type_id",
        existing_type=sa.VARCHAR(length=256),
        nullable=True,
    )
    op.alter_column("documents", "title", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("documents", "view_date", existing_type=sa.DATE(), nullable=True)
    op.alter_column(
        "documents", "external_id", existing_type=sa.VARCHAR(length=256), nullable=True
    )
    op.alter_column(
        "documents", "date_of_publication", existing_type=sa.DATE(), nullable=True
    )
    op.alter_column(
        "documents", "date_of_signing", existing_type=sa.DATE(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "documents", "date_of_signing", existing_type=sa.DATE(), nullable=False
    )
    op.alter_column(
        "documents", "date_of_publication", existing_type=sa.DATE(), nullable=False
    )
    op.alter_column(
        "documents", "external_id", existing_type=sa.VARCHAR(length=256), nullable=False
    )
    op.alter_column("documents", "view_date", existing_type=sa.DATE(), nullable=False)
    op.alter_column("documents", "title", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "documents",
        "document_type_id",
        existing_type=sa.VARCHAR(length=256),
        nullable=False,
    )
    op.alter_column(
        "documents",
        "signatory_authority_id",
        existing_type=sa.VARCHAR(length=256),
        nullable=False,
    )
    op.alter_column(
        "documents", "document_date", existing_type=sa.DATE(), nullable=False
    )
    op.alter_column("documents", "name", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "documents", "pdf_file_length", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "documents", "pages_count", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("documents", "complex_name", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "documents", "eo_number", existing_type=sa.VARCHAR(length=16), nullable=False
    )
    # ### end Alembic commands ###
