"""remove from table block field name and short_name

Revision ID: ab93ea3bf860
Revises: fd383bf7bcf9
Create Date: 2024-05-02 16:46:11.394500

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab93ea3bf860"
down_revision: Union[str, None] = "fd383bf7bcf9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "blocks_id_name_short_name_id_organ_id_reg_key", "blocks", type_="unique"
    )
    op.create_unique_constraint(None, "blocks", ["id", "id_organ", "id_reg"])
    op.drop_column("blocks", "name")
    op.drop_column("blocks", "short_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "blocks",
        sa.Column(
            "short_name", sa.VARCHAR(length=64), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "blocks",
        sa.Column("name", sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "blocks", type_="unique")
    op.create_unique_constraint(
        "blocks_id_name_short_name_id_organ_id_reg_key",
        "blocks",
        ["id", "name", "short_name", "id_organ", "id_reg"],
    )
    # ### end Alembic commands ###
