"""add: New field is_valid for documents table

Revision ID: b319e63290d6
Revises: 2fe3a80dfcf0
Create Date: 2025-04-07 19:58:54.700400

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b319e63290d6"
down_revision: Union[str, None] = "2fe3a80dfcf0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("is_valid", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "is_valid")
    # ### end Alembic commands ###
