"""fix: documents change unique constraint

Revision ID: de5a5de4e01f
Revises: 52436d970dae
Create Date: 2025-03-19 12:33:53.332764

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de5a5de4e01f"
down_revision: Union[str, None] = "52436d970dae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("documents_id_eo_number_key", "documents", type_="unique")
    op.drop_index("idx_documents_eo_number", table_name="documents")
    op.create_unique_constraint("uq_documents_eo_number", "documents", ["eo_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_documents_eo_number", "documents", type_="unique")
    op.create_index("idx_documents_eo_number", "documents", ["eo_number"], unique=True)
    op.create_unique_constraint(
        "documents_id_eo_number_key", "documents", ["id", "eo_number"]
    )
    # ### end Alembic commands ###
