"""fix: add id_type field to documents table

Revision ID: d16819e40ac7
Revises: a0d7724d134d
Create Date: 2025-03-19 11:23:01.450234

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d16819e40ac7"
down_revision: Union[str, None] = "a0d7724d134d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("id_type", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "documents", "types", ["id_type"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_column("documents", "id_type")
    # ### end Alembic commands ###
