"""fix: For document date -> datetime

Revision ID: 86a1befb44da
Revises: 2b039fe8b35f
Create Date: 2025-03-19 17:10:21.460097

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86a1befb44da"
down_revision: Union[str, None] = "2b039fe8b35f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
