"""uq_documents_eo_number_id_reg

Revision ID: d88b8c883483
Revises: 79d0cf2bb82c
Create Date: 2025-03-20 21:37:57.017879

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d88b8c883483"
down_revision: Union[str, None] = "79d0cf2bb82c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_documents_eo_number", table_name="documents")
    op.drop_constraint("uq_documents_eo_number", "documents", type_="unique")
    op.create_unique_constraint(
        "uq_documents_eo_number_id_reg", "documents", ["eo_number", "id_reg"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_documents_eo_number_id_reg", "documents", type_="unique")
    op.create_unique_constraint("uq_documents_eo_number", "documents", ["eo_number"])
    op.create_index("idx_documents_eo_number", "documents", ["eo_number"], unique=True)
    # ### end Alembic commands ###
