"""

Revision ID: 79d0cf2bb82c
Revises: 4a1cfd94ba6f
Create Date: 2025-03-20 13:18:53.652290

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79d0cf2bb82c"
down_revision: Union[str, None] = "4a1cfd94ba6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "documents",
        "eo_number",
        existing_type=sa.VARCHAR(length=16),
        type_=sa.String(length=32),
        existing_nullable=True,
    )
    op.create_unique_constraint("uq_documents_eo_number", "documents", ["eo_number"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_documents_eo_number", "documents", type_="unique")
    op.alter_column(
        "documents",
        "eo_number",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=16),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
