"""fix: исправил уникальные значения в types

Revision ID: 3ba6d9347264
Revises: e6c07e3193af
Create Date: 2025-03-18 18:49:38.700532

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ba6d9347264"
down_revision: Union[str, None] = "e6c07e3193af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_regions_code", table_name="regions")
    op.drop_index("idx_regions_external_id", table_name="regions")
    op.drop_constraint("uq_regions_name_code", "regions", type_="unique")
    op.create_unique_constraint("uq_regions_id_code", "regions", ["id", "code"])
    op.drop_constraint("uq_types_name_external_id", "types", type_="unique")
    op.create_unique_constraint(
        "uq_types_id_external_id", "types", ["id", "external_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_types_id_external_id", "types", type_="unique")
    op.create_unique_constraint(
        "uq_types_name_external_id", "types", ["name", "external_id"]
    )
    op.drop_constraint("uq_regions_id_code", "regions", type_="unique")
    op.create_unique_constraint("uq_regions_name_code", "regions", ["name", "code"])
    op.create_index("idx_regions_external_id", "regions", ["external_id"], unique=False)
    op.create_index("idx_regions_code", "regions", ["code"], unique=False)
    # ### end Alembic commands ###
