"""fix: сделал индекс региона по code

Revision ID: 308d2cbb0680
Revises: d86e7486f01f
Create Date: 2025-03-18 11:51:01.460515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "308d2cbb0680"
down_revision: Union[str, None] = "d86e7486f01f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_regions_external_id", table_name="regions")
    op.create_index("idx_regions_external_id", "regions", ["code"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_regions_external_id", table_name="regions")
    op.create_index("idx_regions_external_id", "regions", ["external_id"], unique=True)
    # ### end Alembic commands ###
