"""fix: убрал индекс regions code

Revision ID: 05be72cc8c88
Revises: 3ba6d9347264
Create Date: 2025-03-19 10:27:05.711404

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "05be72cc8c88"
down_revision: Union[str, None] = "3ba6d9347264"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_regions_code_unique", table_name="regions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_regions_code_unique", "regions", ["code"], unique=True)
    # ### end Alembic commands ###
