"""add: For document add field updated_at

Revision ID: 2b039fe8b35f
Revises: de5a5de4e01f
Create Date: 2025-03-19 16:37:06.881519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b039fe8b35f"
down_revision: Union[str, None] = "de5a5de4e01f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("updated_at", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "updated_at")
    # ### end Alembic commands ###
