"""add: uq_districts_id_name

Revision ID: a6ac0438d389
Revises: 7b972c09556b
Create Date: 2025-03-18 18:08:56.009594

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a6ac0438d389"
down_revision: Union[str, None] = "7b972c09556b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("districts_id_name_key", "districts", type_="unique")
    op.create_unique_constraint("uq_districts_id_name", "districts", ["id", "name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_districts_id_name", "districts", type_="unique")
    op.create_unique_constraint("districts_id_name_key", "districts", ["id", "name"])
    # ### end Alembic commands ###
