"""fix: Изменил длину поля code в Regions

Revision ID: d86e7486f01f
Revises: 7f1199596b04
Create Date: 2025-03-18 11:29:24.696890

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d86e7486f01f"
down_revision: Union[str, None] = "7f1199596b04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "regions",
        "code",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=32),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "regions",
        "code",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
