"""

Revision ID: 4a1cfd94ba6f
Revises: b69820b7ddae
Create Date: 2025-03-20 13:12:34.692156

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a1cfd94ba6f"
down_revision: Union[str, None] = "b69820b7ddae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_documents_eo_number", "documents", type_="unique")
    op.create_index("idx_documents_eo_number", "documents", ["eo_number"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_documents_eo_number", table_name="documents")
    op.create_unique_constraint("uq_documents_eo_number", "documents", ["eo_number"])
    # ### end Alembic commands ###
