"""add: Index

Revision ID: 2fe3a80dfcf0
Revises: eaccd21637a3
Create Date: 2025-03-31 09:55:47.628294

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2fe3a80dfcf0"
down_revision: Union[str, None] = "eaccd21637a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_documents_id_reg", "documents", ["id_reg"], unique=False)
    op.create_index("idx_documents_id_type", "documents", ["id_type"], unique=False)
    op.create_index("idx_documents_view_date", "documents", ["view_date"], unique=False)
    op.create_index("idx_regions_id_dist", "regions", ["id_dist"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_regions_id_dist", table_name="regions")
    op.drop_index("idx_documents_view_date", table_name="documents")
    op.drop_index("idx_documents_id_type", table_name="documents")
    op.drop_index("idx_documents_id_reg", table_name="documents")
    # ### end Alembic commands ###
