"""

Revision ID: b69820b7ddae
Revises: 179cd4a6c9dc
Create Date: 2025-03-19 18:31:48.594862

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b69820b7ddae"
down_revision: Union[str, None] = "179cd4a6c9dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "document_type_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column(
            "document_type_id",
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
