"""fix: For document add field number

Revision ID: 179cd4a6c9dc
Revises: 86a1befb44da
Create Date: 2025-03-19 17:58:32.008426

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "179cd4a6c9dc"
down_revision: Union[str, None] = "86a1befb44da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("number", sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "number")
    # ### end Alembic commands ###
