"""fix: изменил уникальное ограничение в таблицах types и regions

Revision ID: f5583e7095ca
Revises: 05be72cc8c88
Create Date: 2025-03-19 10:38:07.557479

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5583e7095ca"
down_revision: Union[str, None] = "05be72cc8c88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_regions_id_code", "regions", type_="unique")
    op.create_unique_constraint("uq_regions_external_id", "regions", ["external_id"])
    op.drop_constraint("uq_types_id_external_id", "types", type_="unique")
    op.create_unique_constraint("uq_types_external_id", "types", ["external_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_types_external_id", "types", type_="unique")
    op.create_unique_constraint(
        "uq_types_id_external_id", "types", ["id", "external_id"]
    )
    op.drop_constraint("uq_regions_external_id", "regions", type_="unique")
    op.create_unique_constraint("uq_regions_id_code", "regions", ["id", "code"])
    # ### end Alembic commands ###
