"""fix: add id_reg field to documents table

Revision ID: a0d7724d134d
Revises: f5583e7095ca
Create Date: 2025-03-19 11:21:19.276910

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a0d7724d134d"
down_revision: Union[str, None] = "f5583e7095ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("documents", sa.Column("id_reg", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "documents", "regions", ["id_reg"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_column("documents", "id_reg")
    # ### end Alembic commands ###
