"""add: New fields for table documents

Revision ID: f5bf60e49a8d
Revises: b319e63290d6
Create Date: 2025-09-02 21:55:41.048346

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f5bf60e49a8d"
down_revision: Union[str, None] = "b319e63290d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("is_spellchek_valid", sa.Boolean(), nullable=True)
    )
    op.add_column("documents", sa.Column("ocr_name", sa.Text(), nullable=True))
    op.add_column("documents", sa.Column("ocr_similarity", sa.Float(), nullable=True))
    op.add_column("documents", sa.Column("spellcheck_errors", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "spellcheck_errors")
    op.drop_column("documents", "ocr_similarity")
    op.drop_column("documents", "ocr_name")
    op.drop_column("documents", "is_spellchek_valid")
    # ### end Alembic commands ###
