"""in organs add index

Revision ID: de594b6c22dd
Revises: 764fd824c0e5
Create Date: 2024-04-18 00:04:53.820252

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de594b6c22dd"
down_revision: Union[str, None] = "764fd824c0e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_external_id", "organs", ["external_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_external_id", table_name="organs")
    # ### end Alembic commands ###
