"""in organs change  unique constraint

Revision ID: 764fd824c0e5
Revises: 14f755b9705e
Create Date: 2024-04-17 23:46:07.045846

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "764fd824c0e5"
down_revision: Union[str, None] = "14f755b9705e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "organs_id_name_short_name_external_id_code_key", "organs", type_="unique"
    )
    op.create_unique_constraint(None, "organs", ["id", "name", "external_id", "code"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "organs", type_="unique")
    op.create_unique_constraint(
        "organs_id_name_short_name_external_id_code_key",
        "organs",
        ["id", "name", "short_name", "external_id", "code"],
    )
    # ### end Alembic commands ###
