"""in organs alter column parent_id

Revision ID: d5f83ef37a65
Revises: 0949e15d9247
Create Date: 2024-04-17 23:11:02.537332

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d5f83ef37a65"
down_revision: Union[str, None] = "0949e15d9247"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organs", sa.Column("parent_id", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organs", "parent_id")
    # ### end Alembic commands ###
