"""add index for regions table

Revision ID: d9733a70e698
Revises: 5dcf5e60a82e
Create Date: 2024-04-18 13:29:50.000420

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d9733a70e698"
down_revision: Union[str, None] = "5dcf5e60a82e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_external_id", "regions", ["external_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_external_id", table_name="regions")
    # ### end Alembic commands ###
