"""in organs alter column external_id

Revision ID: 0949e15d9247
Revises: d0f3aac55ec2
Create Date: 2024-04-17 23:04:23.590900

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0949e15d9247"
down_revision: Union[str, None] = "d0f3aac55ec2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organs", sa.Column("external_id", sa.String(length=64), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organs", "external_id")
    # ### end Alembic commands ###
