"""in organs alter unique external_id

Revision ID: 74bc7ebad04c
Revises: d5f83ef37a65
Create Date: 2024-04-17 23:30:27.765347

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74bc7ebad04c"
down_revision: Union[str, None] = "d5f83ef37a65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("organs_id_name_short_name_code_key", "organs", type_="unique")
    op.create_unique_constraint(
        None, "organs", ["id", "name", "short_name", "code", "external_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "organs", type_="unique")
    op.create_unique_constraint(
        "organs_id_name_short_name_code_key",
        "organs",
        ["id", "name", "short_name", "code"],
    )
    # ### end Alembic commands ###
