"""in organs change  unique constraint

Revision ID: 14f755b9705e
Revises: 8b34c669c41f
Create Date: 2024-04-17 23:42:20.659195

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "14f755b9705e"
down_revision: Union[str, None] = "8b34c669c41f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("organs_id_external_id_key", "organs", type_="unique")
    op.create_unique_constraint(
        None, "organs", ["id", "name", "short_name", "external_id", "code"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "organs", type_="unique")
    op.create_unique_constraint(
        "organs_id_external_id_key", "organs", ["id", "external_id"]
    )
    # ### end Alembic commands ###
