"""empty message

Revision ID: 5dcf5e60a82e
Revises: de594b6c22dd
Create Date: 2024-04-18 11:53:48.720292

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5dcf5e60a82e"
down_revision: Union[str, None] = "de594b6c22dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("eo_number", sa.String(length=16), nullable=False),
        sa.Column("hash", sa.String(length=256), nullable=True),
        sa.Column("pages_count", sa.Integer(), nullable=False),
        sa.Column("date_of_publication", sa.Date(), nullable=False),
        sa.Column("date_of_signing", sa.Date(), nullable=False),
        sa.Column("id_doc_type_block", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_doc_type_block"],
            ["document_types__blocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "name", "eo_number"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("documents")
    # ### end Alembic commands ###
