name: "Развертывание на удаленный сервер"

on:
  push:
    branches: ["prod"]
  pull_request:
    branches: ["prod"]

env:
  DOCKER_COMPOSE_FILE: "docker-compose.prod.yml"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Получение кода
        uses: actions/checkout@v4

      - name: Остановка всех контейнеров
        run: |
          echo "Остановка всех контейнеров..."
          docker compose --file $DOCKER_COMPOSE_FILE down || exit

      # - name: Удаление неиспользуемых томов
      #   run: |
      #     echo "Удаление неиспользуемых томов..."
      #     docker volume rm $(docker volume ls -q) || true

      - name: Запуск контейнеров
        run: |
          echo "Запуск новых контейнеров..."
          docker compose --file $DOCKER_COMPOSE_FILE up -d --build || exit

      # - name: Инициализация базы данных
      #   run: fish ./database-init-docker-prod.sh || exit
